### ISSUE TITLE
Indexing error

### ISSUE THREAD

**Issue by wyliechee** [natekupp/ffx#25]
FFX stops working (for Python 3.5.1) a few days ago, due to an array indexing error. 

This is due to core.py at line 865: 
st, fin, num=ss.numAlphas() * 10)[::-1][:ss.numAlphas() / 4] 
shoud be changed as:
st, fin, num=ss.numAlphas() * 10)[::-1][:int(ss.numAlphas() / 4)]

Cheers,

**Comment by natekupp** [comment]
hey! thanks for flagging - want to submit a PR?

**Comment by jmmcd** [comment]
This was fixed in 9973408.
