### ISSUE TITLE
AttributeError: module 'ffx' has no attribute 'run'

### ISSUE THREAD

**Issue by tawe141** [natekupp/ffx#26]
The error occurs when I simply try to run the example in the readme. I'm running Anaconda 4.4.0, Python 3.6. Is the Python version the issue?

**Comment by jmmcd** [comment]
I'm on Py3.6 too and no problem.

Do you mean this example?

```
	import numpy as np
	import ffx

	train_X = np.array( [ (1.5,2,3), (4,5,6) ] ).T
	train_y = np.array( [1,2,3])

	test_X = np.array( [ (5.241,1.23, 3.125), (1.1,0.124,0.391) ] ).T
	test_y = np.array( [3.03,0.9113,1.823])

	models = ffx.run(train_X, train_y, test_X, test_y, ["predictor_a", "predictor_b"])
	for model in models:
	    yhat = model.simulate(test_X)
	    print model
```

Have you pasted that directly into a file and run it, or something different? The error you've quoted sounds like an unusual import.

**Comment by Ohjeah** [comment]
Is your example file (or any other file in the current directory) named "ffx.py" ?
