### ISSUE TITLE
version number bump and pypi upgrade?

### ISSUE THREAD

**Issue by dvolgyes** [natekupp/ffx#29]
Hi,

A few months ago there was a python3 division fix.
However, i think the pypi package wasn't updated.

**Comment by bencardoen** [comment]
Same here, would appreciate the version bump for the fix.

**Comment by jmmcd** [comment]
Can you please test the new version in pypi? I've uploaded 1.3.7 but I'm not sure if I got it right.

**Comment by dvolgyes** [comment]
It seems OK for me, both for python2 and python3.
