### ISSUE TITLE
How to identify the prediction model used from FFX.models_ via the Scikit-Learn API?

### ISSUE THREAD

**Issue by Rafail-Karkanis** [natekupp/ffx#55]
I am using the Scikit-Learn interface and have successfully printed the entire Pareto front through FFX.models_. However, I am uncertain about how to identify and print the specific model used for predictions.

The README.md states that FFX selects the model with the highest accuracy and complexity for predictions. Could you please clarify which model from the FFX.models_ list this corresponds to? Is it the last model in the list?

Thank you in advance.

**Comment by jmmcd** [comment]
Yes, it's the last one. It will be the longest equation in the list.


```
Num bases,Test error (%),Model
0, 62.4453, 3.50
1, 11.4284, 0.640 + 0.817_x^2
2, 1.6635, 0.0846 + 0.972_x^2 + 0.00984_x
4, 0.7507, (0.0973 + 0.523_x^2 + 0.440_x^2) / (1.0 - 0.00214_x - 0.00168*x)
```
